version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: rudi-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rudi_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Optional: Adminer for database UI (lighter than pgAdmin)
  adminer:
    image: adminer
    container_name: rudi-adminer
    restart: always
    ports:
      - "8089:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pepa-linha
    depends_on:
      - postgres

volumes:
  postgres_data:
    name: rudi_postgres_data