name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Type check
        run: npm run typecheck --if-present

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          # Provide safe defaults for public envs used in build
          NEXT_PUBLIC_SUPABASE_URL: 'https://example.supabase.co'
          NEXT_PUBLIC_SUPABASE_ANON_KEY: 'anon_key'
        run: npm run build

